zuul:
  ignored-service: "*"  #routes 에 적혀있는 서비스들을 제외하곤 모두 무시한다
  prefix: /api  #Zuul 에 의해 routing 되는 모든 service의 Endpoint를 /api~ 로 묶는다
  routes:
    spring-cloud-blog:
        path: /blog/**
        serviceId: spring-cloud-blog
        stripPrefix: false
    auth-center:
      path: /login/**
      url: http://27.96.135.235:8760/
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: false
  ribbonIsolationStrategy: THREAD  #각각의 서비스르의 쓰레드 풀을 독립적으로 설정하겠다 라는 뜻..
  threadPool:
    useSeparateThreadPools: true



hystrix:
  command:
    story-service:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 20000

spring-cloud-blog:
  ribbon:
    eureka:
      enabled: true
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
    ConnectTimeout: 5000
    ReadTimeout: 5000

    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100

eureka:
  client:
    healthcheck: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://27.96.135.235:8761}/eureka/
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      perferIpAddress: true

server:
  port: 4000
